name: Generator

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Environment Setup
        id: step1
        shell: bash
        run: |
          echo "version=$(curl -s -L 'https://api.carbonmod.gg/version?id=docs&token=${{secrets.VERSIONS_TOKEN}}')" >> $GITHUB_OUTPUT
          
      - name: Process
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%\tools
          Generate.bat
          
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Archive
          path: |
            tools\Server\carbon

      - name: FTP Upload (rust/blueprints.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/blueprints.json"
          dest: "meta/rust/blueprints.json"

      - name: FTP Upload (rust/entities.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/entities.json"
          dest: "meta/rust/entities.json"

      - name: FTP Upload (rust/items.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/items.json"
          dest: "meta/rust/items.json"

      - name: FTP Upload (rust/loot-tables.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/loot-tables.json"
          dest: "meta/rust/loot-tables.json"

      - name: FTP Upload (rust/prefabs.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/prefabs.json"
          dest: "meta/rust/prefabs.json"

      - name: FTP Upload (rust/convars.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/rust_convars.json"
          dest: "meta/rust/convars.json"

      - name: FTP Upload (rust/commands.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/rust_commands.json"
          dest: "meta/rust/commands.json"

      - name: FTP Upload (carbon/hooks.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/hooks.json"
          dest: "meta/carbon/hooks.json"

      - name: FTP Upload (carbon/commands.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/commands.json"
          dest: "meta/carbon/commands.json"

      - name: FTP Upload (carbon/convars.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/convars.json"
          dest: "meta/carbon/convars.json"

      - name: FTP Upload (carbon/switches.json)
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: api@carbonmod.gg
          password: ${{ secrets.FTP_PWD }}
          host: ${{ secrets.FTP_IP }}
          src: "tools/Server/carbon/results/switches.json"
          dest: "meta/carbon/switches.json"
